apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendation-server
  namespace: zoochacha
spec:
  replicas: 1  # 서버는 확장 가능하도록 설정
  selector:
    matchLabels:
      app: recommendation-server
  template:
    metadata:
      labels:
        app: recommendation-server
    spec:
      containers:
        - name: recommendation-server
          image: 651706756261.dkr.ecr.ap-northeast-2.amazonaws.com/recommendation_service:3
          imagePullPolicy: Always
          env:
            - name: DB_HOST
              value: "mysql.zoochacha-db.svc.cluster.local"
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: "zoochacha"
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              value: ""
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: recommendation-server
  namespace: zoochacha
spec:
  selector:
    app: recommendation-server
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP